ARG ORG=cynix
FROM dockcross/base:latest

LABEL maintainer="cynix@cynix.org"

ENV FREEBSD_ARCH=aarch64
ENV FREEBSD_MACHINE=arm64
ENV FREEBSD_MACHINE_ARCH=aarch64

ENV RUSTUP_TOOLCHAIN=nightly

#include "common.freebsd"
#include "common.label-and-env"
