ARG ORG=cynix
FROM dockcross/base:latest

LABEL maintainer="cynix@cynix.org"

ENV FREEBSD_ARCH=x86_64
ENV FREEBSD_MACHINE=amd64
ENV FREEBSD_MACHINE_ARCH=amd64

#include "common.freebsd"
#include "common.label-and-env"
