set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_VERSION "$ENV{FREEBSD_VERSION}")

if ("$ENV{FREEBSD_ARCH}" STREQUAL "x86_64")
  set(CMAKE_SYSTEM_PROCESSOR "amd64")
elseif ("$ENV{FREEBSD_ARCH}" STREQUAL "aarch64")
  set(CMAKE_SYSTEM_PROCESSOR "arm64")
else()
  set(CMAKE_SYSTEM_PROCESSOR "$ENV{FREEBSD_ARCH}")
endif()

set(CMAKE_SYSROOT "$ENV{FREEBSD_SYSROOT}")

set(CMAKE_ASM_COMPILER $ENV{CC})
set(CMAKE_ASM_COMPILER_TARGET "$ENV{FREEBSD_TRIPLE}")

set(CMAKE_C_COMPILER $ENV{CC})
set(CMAKE_C_COMPILER_TARGET "$ENV{FREEBSD_TRIPLE}")

set(CMAKE_CXX_COMPILER $ENV{CXX})
set(CMAKE_CXX_COMPILER_TARGET "$ENV{FREEBSD_TRIPLE}")

set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_STATIC_LINKER_FLAGS_INIT "-fuse-ld=lld")
